name: 05-02 Event Filter & Activity Types

on:
 pull_request:
    types:
      - closed
    branches:
      - main


jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
        - name: Show the triggering event
          run: |
           echo "Running whenever a PR is closed"
           echo "This workflow was triggered by the event: ${{ github.event_name }} and  action is ${{ github.event.action }}"